apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-mysql
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysqldump
              image: quay.io/bszeti/mysql:9.6
              command:
                - /bin/bash
                - -c
                - |
                  set -eo pipefail

                  # Get server-uuid
                  SERVER_UUID=$(mysql -h $MYSQL_SERVICE -uroot -p$(cat $MYSQL_ROOT_PASSWORD_FILE) -sN -e "SELECT @@global.server_uuid;")
                  MYSQL_DUMP_DIR=/tmp/$SERVER_UUID/mysql-dump
                  mkdir -p $MYSQL_DUMP_DIR
                  echo "MYSQL_DUMP_DIR:" $MYSQL_DUMP_DIR

                  # Backup non-system databases
                  DATABASES=$(mysql -h $MYSQL_SERVICE -uroot -p$(cat $MYSQL_ROOT_PASSWORD_FILE) -sN -e "SHOW DATABASES WHERE \`Database\` NOT IN ('mysql', 'performance_schema', 'information_schema', 'sys');")
                  echo DATABASES: $DATABASES
                  mysqldump -h $MYSQL_SERVICE -uroot -p$(cat $MYSQL_ROOT_PASSWORD_FILE) --single-transaction --source-data=2 --flush-logs --set-gtid-purged=OFF --routines --events --databases $DATABASES | gzip > $MYSQL_DUMP_DIR/mysqldump-$(date +%Y-%m-%d-%H-%M-%S).sql.gz 
                  
                  # Move to upload directory
                  mv /tmp/$SERVER_UUID /backup/upload/ 
              env:
                - name: MYSQL_ROOT_PASSWORD_FILE
                  value: /mysql-credentials/mysql-root-password
                - name: MYSQL_SERVICE
                  value: test-mysql-secondary
              volumeMounts:
                - name: mysql-credentials
                  mountPath: /mysql-credentials             
                - name: shared-volume
                  mountPath: /backup/upload
                  
            - name: upload
              image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
              command:
                - /bin/bash
                - -c
                - |
                  set -eo pipefail
                  echo "Starting upload container"
                  UPLOAD_DIR=/backup/upload

                  # TODO: Job can get stuck waiting here even if the other container failed. Should use once container only.
                  while [ -z "$(ls -A $UPLOAD_DIR)" ]; do
                    echo "Waiting for upload files to be created"
                    sleep 5
                  done
                  
                  gcloud auth activate-service-account --key-file=/gcp-credentials/sa.json --project=$GCP_PROJECT_ID
                  gcloud storage rsync -r $UPLOAD_DIR $BUCKET_PATH
                  
              env:
                - name: CLOUDSDK_CONFIG
                  # Needs to be a writable directory
                  value: /tmp/config          
                - name: GCP_PROJECT_ID
                  value: "rhpds-345620"
                - name: BUCKET_PATH
                  value: "gs://my-bucket-n9dps/mysql-test"        
              volumeMounts:
                - name: gcp-credentials
                  mountPath: /gcp-credentials             
                - name: shared-volume
                  mountPath: /backup/upload            
          volumes:
            - name: mysql-credentials
              secret:
                secretName: test-mysql
                items:
                  - key: mysql-root-password
                    path: mysql-root-password
            - name: gcp-credentials
              secret:
                secretName: gcp-credentials                    
            - name: shared-volume
              emptyDir: {}
          activeDeadlineSeconds: 3600 # Job deadline 1 hours
          restartPolicy: Never
      # Don't retry new Pod on failure
      backoffLimit: 0