apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-mysqldump
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      # Don't retry new Pod on failure
      backoffLimit: 0
      activeDeadlineSeconds: 14400 # Job deadline 4 hours
      template:
        spec:
          restartPolicy: Never        
          containers:
            - name: mysqldump
              image: quay.io/bszeti/mysql:9.6
              command:
                - /bin/bash
                - -c
                - |
                  set -eo pipefail
                  # Create a file to indicate that the container has terminated
                  trap 'touch $SHARED_VOLUME/terminated' ERR

                  # Get server-uuid
                  SERVER_UUID=$(mysql -h $MYSQL_SERVICE -uroot -p$(cat $MYSQL_ROOT_PASSWORD_FILE) -sN -e "SELECT @@global.server_uuid;")
                  MYSQL_DUMP_DIR=/tmp/$SERVER_UUID/mysql-dump
                  mkdir -p $MYSQL_DUMP_DIR
                  echo "MYSQL_DUMP_DIR:" $MYSQL_DUMP_DIR

                  # Backup non-system databases
                  DATABASES=$(mysql -h $MYSQL_SERVICE -uroot -p$(cat $MYSQL_ROOT_PASSWORD_FILE) -sN -e "SHOW DATABASES WHERE \`Database\` NOT IN ('mysql', 'performance_schema', 'information_schema', 'sys');")
                  echo DATABASES: $DATABASES
                  time mysqldump -h $MYSQL_SERVICE -uroot -p$(cat $MYSQL_ROOT_PASSWORD_FILE) --single-transaction --source-data=2 --flush-logs --set-gtid-purged=OFF --routines --events --databases $DATABASES | gzip > $MYSQL_DUMP_DIR/mysqldump-$(date +%Y%m%d%H%M%S).sql.gz 
                  
                  # Move to upload directory
                  mv /tmp/$SERVER_UUID $SHARED_VOLUME/ 
              env:
                - name: MYSQL_ROOT_PASSWORD_FILE
                  value: /mysql-credentials/mysql-root-password
                - name: MYSQL_SERVICE
                  value: test-mysql-secondary
                - name: SHARED_VOLUME
                  value: /backup/upload
              volumeMounts:
                - name: mysql-credentials
                  mountPath: /mysql-credentials
                - name: shared-volume
                  mountPath: /backup/upload
                 
            - name: upload
              image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
              command:
                - /bin/bash
                - -c
                - |
                  set -eo pipefail
                  echo "Starting upload container"
                  gcloud auth activate-service-account --key-file=/gcp-credentials/sa.json --project=$GCP_PROJECT_ID

                  while [ -z "$(ls -A $SHARED_VOLUME)" ]; do
                    echo "Waiting for mysql dump file to be created"
                    sleep 5
                  done
                  [[ -f $SHARED_VOLUME/terminated ]] && echo "Terminated by other container" && exit 0
                  
                  # Upload files to bucket
                  time gcloud storage rsync -r $SHARED_VOLUME $BUCKET_PATH
              env:
                - name: CLOUDSDK_CONFIG
                  # Needs to be a writable directory
                  value: /tmp/config          
                - name: GCP_PROJECT_ID
                  value: "rhpds-345620"
                - name: BUCKET_PATH
                  value: "gs://my-bucket-n9dps/mysql-test"  
                - name: SHARED_VOLUME
                  value: /backup/upload
              volumeMounts:
                - name: gcp-credentials
                  mountPath: /gcp-credentials             
                - name: shared-volume
                  mountPath: /backup/upload    
                     
          volumes:
            - name: mysql-credentials
              secret:
                secretName: test-mysql
                items:
                  - key: mysql-root-password
                    path: mysql-root-password
            - name: gcp-credentials
              secret:
                secretName: gcp-credentials                    
            - name: shared-volume
              emptyDir: {}

      