apiVersion: v1
kind: ConfigMap
metadata: 
  name: scripts-sidecars
data:
  backup-mysql-bin.sh: |
      set -eo pipefail
      trap 'echo "Terminating..."; exit' TERM
      echo "Starting backup-mysql-bin sidecar"

      # User server-uuid and creation timestamp to create a unique bucket path
      while [ ! -f /data/data/auto.cnf ]; do
        echo "Waiting for auto.cnf to be created"
        sleep 5
      done
      # SERVER_UUID_DATE=$(date -d "@$(stat -c %W /data/data/auto.cnf)" +%Y-%m-%d-%H-%M-%S)
      SERVER_UUID=$(grep -oP 'server-uuid=\K[^ ]+' /data/data/auto.cnf)
      BUCKET_PATH_SERVER=$BUCKET_PATH/$SERVER_UUID
      echo "BUCKET_PATH_SERVER:" $BUCKET_PATH_SERVER

      gcloud auth activate-service-account --key-file=/gcp-credentials/sa.json --project=$GCP_PROJECT_ID
      
      cd /data/data
      while true; do
        # Search for mysql-bin.[index] files in /data/data, exclude the last one
        BIN_FILES=$(find * -name "mysql-bin.[0-9]*" -type f | sort -r | tail -n +2 | sort )
        # Search for existing mysql-bin files in the bucket
        BIN_FILES_IN_BUCKET=$(gcloud storage ls "$BUCKET_PATH_SERVER/mysql-bin/*" 2>/dev/null || true)
        # echo "BIN_FILES:" $BIN_FILES
        # echo "BIN_FILES_IN_BUCKET:" $BIN_FILES_IN_BUCKET

        for file in $BIN_FILES; do
          # Uploading file to bucket if it's not there yet
          if ! echo $BIN_FILES_IN_BUCKET | grep -qw "$file"; then
            # Compress and upload
            gzip -c $file >/tmp/$file.gz
            gcloud storage cp /tmp/$file.gz $BUCKET_PATH_SERVER/mysql-bin/
            rm -f /tmp/$file.gz
          fi
        done

        # Sleep observing TERM signal
        sleep $MYSQL_BIN_UPLOAD_PERIOD & wait $!
      done
  mysql-flush-logs.sh: |
      set -eo pipefail
      trap 'echo "Terminating..."; exit' TERM
      echo "Starting mysql-flush-logs sidecar"
      while true; do
        sleep $MYSQL_BIN_FLUSH_PERIOD & wait $!
        mysql -h 127.0.0.1 -uroot -p$(cat $MYSQL_MASTER_ROOT_PASSWORD_FILE) -e "FLUSH BINARY LOGS;"
      done