apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
stringData:
  sa.json: |
    {
        "type": "service_account",
        "private_key_id": "215de796c53765ae7b0b00f9fbba5df656472d0a",
        ...
    }