
architecture: replication
global:
  security:
    # Allow non-original image
    allowInsecureImages: true
auth:
  database: db1
  rootPassword: myrootsecret
  username: myuser
  password: mysecret
image:
  registry: quay.io
  repository: bszeti/mysql
  tag: '9.6'
  pullPolicy: Always
primary:
  pdb:
    create: false
  persistence:
    size: 20Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Delete
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi 
  configuration: |-
    [mysqld]
    authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port={{ .Values.primary.containerPorts.mysql }}
    mysqlx={{ ternary 1 0 .Values.primary.enableMySQLX }}
    mysqlx_port={{ .Values.primary.containerPorts.mysqlx }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8MB4
    slow_query_log=0
    long_query_time=10.0
    {{- if .Values.tls.enabled }}
    ssl_cert=/opt/bitnami/mysql/certs/{{ .Values.tls.certFilename }}
    ssl_key=/opt/bitnami/mysql/certs/{{ .Values.tls.certKeyFilename }}
    {{- if (include "mysql.tlsCACert" .) }}
    ssl_ca={{ include "mysql.tlsCACert" . }}
    {{- end }}
    {{- end }}

    [client]
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
initdbScripts:
  init.sh: |
    [[ "$DB_REPLICATION_MODE" = "slave" ]] && warn "Init script is not run on secondary node. Skipping..." && return
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "
      CREATE DATABASE db2; 
      GRANT ALL PRIVILEGES ON db2.* TO 'myuser'@'%';
      FLUSH PRIVILEGES;
      CREATE TABLE db1.messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        created_at DATETIME,
        message VARCHAR(1000)
      );
      CREATE TABLE db2.messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        created_at DATETIME,
        message VARCHAR(1000)
      );
    "
#   init.sql: |
#     -- Broken with MySQL v9? mysql -u root -p$(cat $MYSQL_ROOT_PASSWORD_FILE) <<<"source /docker-entrypoint-initdb.d/init.sql;"

secondary:
  replicaCount: 1
  pdb:
    create: false
  persistence:
    size: 20Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Delete
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi 
  configuration: |-
    [mysqld]
    authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port={{ .Values.secondary.containerPorts.mysql }}
    mysqlx={{ ternary 1 0 .Values.secondary.enableMySQLX }}
    mysqlx_port={{ .Values.secondary.containerPorts.mysqlx }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8MB4
    slow_query_log=0
    long_query_time=10.0
    {{- if .Values.tls.enabled }}
    ssl_cert=/opt/bitnami/mysql/certs/{{ .Values.tls.certFilename }}
    ssl_key=/opt/bitnami/mysql/certs/{{ .Values.tls.certKeyFilename }}
    {{- if (include "mysql.tlsCACert" .) }}
    ssl_ca={{ include "mysql.tlsCACert" . }}
    {{- end }}
    {{- end }}

    [client]
    port={{ .Values.secondary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port={{ .Values.secondary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  extraVolumes:
    - name: gcp-credentials
      secret:
        secretName: gcp-credentials
  sidecars:
    - name: mysql-flush-logs
      image: quay.io/bszeti/mysql:9.6
      command:
        - /bin/bash
        - -c
        - |
          set -eo pipefail
          trap 'echo "Terminating..."; exit' TERM
          echo "Starting mysql-flush-logs sidecar"
          while true; do
            sleep $MYSQL_BIN_FLUSH_PERIOD & wait $!
            mysql -h 127.0.0.1 -uroot -p$(cat $MYSQL_MASTER_ROOT_PASSWORD_FILE) -e "FLUSH BINARY LOGS;"
          done
      env:
        - name: MYSQL_MASTER_ROOT_PASSWORD_FILE
          value: /mysql-credentials/mysql-root-password
        - name: MYSQL_BIN_FLUSH_PERIOD
          value: "60"
      volumeMounts:
        - name: mysql-credentials
          mountPath: /mysql-credentials
    - name: backup-mysql-bin
      # image: quay.io/bszeti/mysql:9.6
      image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
      command:
        - /bin/bash
        - -c
        - |
          set -eo pipefail
          trap 'echo "Terminating..."; exit' TERM
          echo "Starting backup-mysql-bin sidecar"

          # User server-uuid and creation timestamp to create a unique bucket path
          while [ ! -f /data/data/auto.cnf ]; do
            echo "Waiting for auto.cnf to be created"
            sleep 5
          done
          SERVER_UUID_DATE=$(date -d "@$(stat -c %W /data/data/auto.cnf)" +%Y-%m-%d-%H-%M-%S)
          SERVER_UUID=$(grep -oP 'server-uuid=\K[^ ]+' /data/data/auto.cnf)
          BUCKET_PATH_SERVER=$BUCKET_PATH/$SERVER_UUID_DATE-$SERVER_UUID
          echo "BUCKET_PATH_SERVER:" $BUCKET_PATH_SERVER

          gcloud auth activate-service-account --key-file=/gcp-credentials/sa.json --project=$GCP_PROJECT_ID
          
          cd /data/data
          while true; do
            # Search for mysql-bin.[index] files in /data/data, exclude the last one
            BIN_FILES=$(find ./ -name "mysql-bin.[0-9]*" -type f | sort -r | tail -n +2 | sort )
            # Search for existing mysql-bin files in the bucket
            BIN_FILES_IN_BUCKET=$(gcloud storage ls "$BUCKET_PATH_SERVER/mysql-bin/*" 2>/dev/null || true)
            # echo "BIN_FILES:" $BIN_FILES
            # echo "BIN_FILES_IN_BUCKET:" $BIN_FILES_IN_BUCKET
            for file in $BIN_FILES; do
              filename=$(basename $file)
              if ! echo $BIN_FILES_IN_BUCKET | grep -qw "$filename"; then
                # Uploading file to bucket
                gcloud storage cp $file $BUCKET_PATH_SERVER/mysql-bin/
              fi
            done
            sleep $MYSQL_BIN_UPLOAD_PERIOD & wait $!
          done
      env:
        - name: CLOUDSDK_CONFIG
          # Needs to be a writable directory
          value: /tmp/config
        - name: MYSQL_BIN_UPLOAD_PERIOD
          value: "20"
        - name: GCP_PROJECT_ID
          # value: "my-gcp-project"
          value: "rhpds-345620"
        - name: BUCKET_PATH
          value: "gs://my-bucket-n9dps/mysql-test"
      volumeMounts:
        - name: data
          mountPath: /data
        - name: gcp-credentials
          mountPath: /gcp-credentials

          
tls:
  autoGenerated:
    enabled: false