
architecture: replication
global:
  security:
    # Allow non-original image
    allowInsecureImages: true
auth:
  # Don't autocreate database, because we restore from backup
  createDatabase: false
  rootPassword: myrootsecret
  username: myuser
  password: mysecret
image:
  registry: quay.io
  repository: bszeti/mysql
  tag: '9.6'
  pullPolicy: Always

primary:
  # initdbScripts is removed, because we restore from backup
  pdb:
    create: false
  persistence:
    size: 20Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Delete
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi 
  configuration: |-
    [mysqld]
    authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port={{ .Values.primary.containerPorts.mysql }}
    mysqlx={{ ternary 1 0 .Values.primary.enableMySQLX }}
    mysqlx_port={{ .Values.primary.containerPorts.mysqlx }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    # The default UTF in values.yaml causes a problem with v9.6, skip or use UTF8MB4 instead
    # character-set-server=UTF8MB4
    slow_query_log=0
    long_query_time=10.0
    {{- if .Values.tls.enabled }}
    ssl_cert=/opt/bitnami/mysql/certs/{{ .Values.tls.certFilename }}
    ssl_key=/opt/bitnami/mysql/certs/{{ .Values.tls.certKeyFilename }}
    {{- if (include "mysql.tlsCACert" .) }}
    ssl_ca={{ include "mysql.tlsCACert" . }}
    {{- end }}
    {{- end }}

    [client]
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid


secondary:
  replicaCount: 1
  pdb:
    create: false
  persistence:
    size: 20Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Delete
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi
  configuration: |-
    [mysqld]
    authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port={{ .Values.secondary.containerPorts.mysql }}
    mysqlx={{ ternary 1 0 .Values.secondary.enableMySQLX }}
    mysqlx_port={{ .Values.secondary.containerPorts.mysqlx }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    # character-set-server=UTF8
    slow_query_log=0
    long_query_time=10.0
    {{- if .Values.tls.enabled }}
    ssl_cert=/opt/bitnami/mysql/certs/{{ .Values.tls.certFilename }}
    ssl_key=/opt/bitnami/mysql/certs/{{ .Values.tls.certKeyFilename }}
    {{- if (include "mysql.tlsCACert" .) }}
    ssl_ca={{ include "mysql.tlsCACert" . }}
    {{- end }}
    {{- end }}

    [client]
    port={{ .Values.secondary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port={{ .Values.secondary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  extraVolumes:
    - name: gcp-credentials
      secret:
        secretName: gcp-credentials
    - name: scripts-sidecars
      configMap:
        name: scripts-sidecars
        
  # Backup sidecars - the same as in initial MySQL cluster
  sidecars:
    - name: mysql-flush-logs
      image: quay.io/bszeti/mysql:9.6
      command:
        - /bin/bash
        - /scripts/mysql-flush-logs.sh
      env:
        - name: MYSQL_MASTER_ROOT_PASSWORD_FILE
          value: /mysql-credentials/mysql-root-password
        - name: MYSQL_BIN_FLUSH_PERIOD
          value: "60"
      volumeMounts:
        - name: mysql-credentials
          mountPath: /mysql-credentials
        - name: scripts-sidecars
          mountPath: /scripts/mysql-flush-logs.sh
          subPath: mysql-flush-logs.sh

    - name: backup-mysql-bin
      image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
      command:
        - /bin/bash
        - /scripts/backup-mysql-bin.sh
      env:
        - name: CLOUDSDK_CONFIG
          # Needs to be a writable directory
          value: /tmp/config
        - name: MYSQL_BIN_UPLOAD_PERIOD
          value: "10"
        - name: GCP_PROJECT_ID
          # value: "my-gcp-project"
          value: "rhpds-345620"
        - name: BUCKET_PATH
          value: "gs://my-bucket-n9dps/mysql-test"
      volumeMounts:
        - name: data
          mountPath: /data
        - name: gcp-credentials
          mountPath: /gcp-credentials
        - name: scripts-sidecars
          mountPath: /scripts/backup-mysql-bin.sh
          subPath: backup-mysql-bin.sh

tls:
  autoGenerated:
    enabled: false