
architecture: replication
global:
  security:
    # Allow non-original image
    allowInsecureImages: true
auth:
  database: db1
  rootPassword: myrootsecret
  username: myuser
  password: mysecret
image:
  registry: quay.io
  repository: bszeti/mysql
  tag: '9.6'
  pullPolicy: Always
primary:
  pdb:
    create: false
  persistence:
    size: 20Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Delete
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi 
  configuration: |-
    [mysqld]
    authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port={{ .Values.primary.containerPorts.mysql }}
    mysqlx={{ ternary 1 0 .Values.primary.enableMySQLX }}
    mysqlx_port={{ .Values.primary.containerPorts.mysqlx }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8MB4
    slow_query_log=0
    long_query_time=10.0
    {{- if .Values.tls.enabled }}
    ssl_cert=/opt/bitnami/mysql/certs/{{ .Values.tls.certFilename }}
    ssl_key=/opt/bitnami/mysql/certs/{{ .Values.tls.certKeyFilename }}
    {{- if (include "mysql.tlsCACert" .) }}
    ssl_ca={{ include "mysql.tlsCACert" . }}
    {{- end }}
    {{- end }}

    [client]
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
initdbScripts:
  init.sh: |
    [[ "$DB_REPLICATION_MODE" = "slave" ]] && warn "Init script is not run on secondary node. Skipping..." && return
    echo "Creating databases and tables on primary node."
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "
      CREATE DATABASE db2; 
      GRANT ALL PRIVILEGES ON db2.* TO 'myuser'@'%';
      FLUSH PRIVILEGES;
      CREATE TABLE db1.messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        created_at DATETIME,
        message VARCHAR(1000)
      );
      CREATE TABLE db2.messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        created_at DATETIME,
        message VARCHAR(1000)
      );
    "
#   init.sql: |
#     -- Broken with MySQL v9? mysql -u root -p$(cat $MYSQL_ROOT_PASSWORD_FILE) <<<"source /docker-entrypoint-initdb.d/init.sql;"

secondary:
  replicaCount: 1
  pdb:
    create: false
  persistence:
    size: 20Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Delete
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi 
  configuration: |-
    [mysqld]
    authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port={{ .Values.secondary.containerPorts.mysql }}
    mysqlx={{ ternary 1 0 .Values.secondary.enableMySQLX }}
    mysqlx_port={{ .Values.secondary.containerPorts.mysqlx }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8MB4
    slow_query_log=0
    long_query_time=10.0
    {{- if .Values.tls.enabled }}
    ssl_cert=/opt/bitnami/mysql/certs/{{ .Values.tls.certFilename }}
    ssl_key=/opt/bitnami/mysql/certs/{{ .Values.tls.certKeyFilename }}
    {{- if (include "mysql.tlsCACert" .) }}
    ssl_ca={{ include "mysql.tlsCACert" . }}
    {{- end }}
    {{- end }}

    [client]
    port={{ .Values.secondary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port={{ .Values.secondary.containerPorts.mysql }}
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid

tls:
  autoGenerated:
    enabled: false