# Kubernetes Job to run app inserting rows into a MySQL database
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-insert
  labels:
    app: mysql-insert
spec:
  # Don't retry new Pod on failure
  backoffLimit: 0
  activeDeadlineSeconds: 14400 # Job deadline 4 hours
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: registry.redhat.io/ubi9/python-312:latest
          command:
            - /bin/bash
            - -c
            - |
              pip install -r requirements.txt
              python mysql-insert.py
          env:
            - name: DB_HOST
              value: test-mysql-primary.mysql.svc
            - name: DB_USERNAME
              value: myuser
            - name: DB_PASSWORD
              value: mysecret
            - name: DB_NAME
              value: db1
            - name: BATCH_SIZE
              value: "100"
            - name: BATCH_COUNT
              value: "1200"
            - name: SLEEP_MS
              value: "1000"
            - name: MESSAGE_LENGTH
              value: "1000"
          volumeMounts:
            - name: app
              mountPath: /opt/app-root/src
            
      volumes:
        - name: app
          configMap:
            name: app
        